# Site settings
title: Being One With Zero
email: manasgarg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Manas Gargs Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://beingonewithzero.com" # the base hostname & protocol for your site
twitter_username: manasgarg
github_username:  manasgarg

# Build settings
markdown: kramdown
